<a href="https://colab.research.google.com/github/221230009-bit/rizky-aditia/blob/main/Latihan_pratikum2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# 🧠 LATIHAN 2: PREPROCESSING PIPELINE (NumPy)

import numpy as np

'''TODO: Implementasi Preprocessing Pipeline'''
# Dataset simulasi: 100 samples, 5 features
np.random.seed(42)
X = np.random.randn(100, 5) * 10 + 5  # Menghasilkan data dengan mean sekitar 5 dan std sekitar 10

# 1️⃣ Z-Score Normalization: (x - mean) / std
def z_score_normalization(data):
    """
    Melakukan normalisasi Z-score pada data.

    Args:
        data (np.ndarray): Data input.

    Returns:
        np.ndarray: Data yang sudah dinormalisasi.
    """
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    normalized = (data - mean) / std
    return normalized

X_normalized = z_score_normalization(X)

# 2️⃣ Handle outliers - replace values beyond 3 std with boundaries
def handle_outliers(data, std_threshold=3):
    """
    Menangani outlier dengan mengganti nilai yang berada di luar ambang batas
    standar deviasi dengan batas tersebut.

    Args:
        data (np.ndarray): Data input (sebaiknya sudah dinormalisasi).
        std_threshold (int): Jumlah standar deviasi dari mean untuk batas outlier.

    Returns:
        np.ndarray: Data dengan outlier yang sudah ditangani.
    """
    data_clipped = np.copy(data)
    # Mengganti nilai di atas batas atas dengan batas atas
    data_clipped[data_clipped > std_threshold] = std_threshold
    # Mengganti nilai di bawah batas bawah dengan batas bawah
    data_clipped[data_clipped < -std_threshold] = -std_threshold
    return data_clipped

X_cleaned = handle_outliers(X_normalized)

# 3️⃣ One-hot encoding untuk label kategorikal
def one_hot_encoding(labels):
    """
    Melakukan one-hot encoding pada array label kategorikal.

    Args:
        labels (np.ndarray): Array label kategorikal (berupa integer).

    Returns:
        np.ndarray: Array one-hot encoded.
    """
    # Menentukan jumlah kelas berdasarkan nilai maksimum dalam label
    n_classes = np.max(labels) + 1
    # Membuat array nol dengan ukuran (jumlah sampel, jumlah kelas)
    one_hot = np.zeros((len(labels), n_classes))
    # Mengisi array one-hot pada posisi yang sesuai dengan 1
    one_hot[np.arange(len(labels)), labels] = 1
    return one_hot

# Contoh penggunaan one-hot encoding dengan label simulasi
labels = np.array([0, 1, 2, 0, 1, 2, 0])
one_hot_labels = one_hot_encoding(labels)

# 4️⃣ Train-test split manual tanpa sklearn
def train_test_split_numpy(X, y, test_size=0.2):
    """
    Membagi dataset menjadi subset training dan testing secara manual.

    Args:
        X (np.ndarray): Fitur data.
        y (np.ndarray): Label data.
        test_size (float): Proporsi data yang akan digunakan untuk testing.

    Returns:
        tuple: X_train, X_test, y_train, y_test.
    """
    n_samples = X.shape[0]
    n_test = int(n_samples * test_size)
    indices = np.arange(n_samples)
    np.random.shuffle(indices) # Mengacak indeks
    test_idx = indices[:n_test]
    train_idx = indices[n_test:]
    return X[train_idx], X[test_idx], y[train_idx], y[test_idx]

# Simulasi label random untuk X (agar sesuai dengan jumlah sampel di X)
y = np.random.randint(0, 3, X.shape[0])
X_train, X_test, y_train, y_test = train_test_split_numpy(X, y)

# ✅ Validasi hasil
# Memeriksa apakah shape data setelah normalisasi tetap sama
assert X_normalized.shape == X.shape, "Shape should remain same after normalization"
# Memeriksa apakah mean data setelah normalisasi mendekati 0
assert np.allclose(np.mean(X_normalized, axis=0), 0, atol=1e-10), "Mean should be ~0 after z-score"
# Memeriksa apakah standard deviasi data setelah normalisasi mendekati 1
assert np.allclose(np.std(X_normalized, axis=0), 1, atol=1e-10), "Std should be ~1 after z-score"

print("✅ NumPy operations completed successfully!\n")

# 📊 Menampilkan hasil ringkas
print("Shape Data:")
print("  X:", X.shape)
print("  X_train:", X_train.shape)
print("  X_test:", X_test.shape)

print("\nContoh One-Hot Encoding:")
# Menampilkan beberapa contoh hasil one-hot encoding
print(one_hot_labels[:5])

print("\nContoh Data Normalisasi & Outlier Handling:")
# Menampilkan contoh data sebelum dan sesudah normalisasi dan outlier handling
print("Sebelum (Data Asli):", X[0])
print("Sesudah Normalisasi:", X_normalized[0])
print("Sesudah Outlier Handling:", X_cleaned[0])

✅ NumPy operations completed successfully!

Shape Data:
  X: (100, 5)
  X_train: (80, 5)
  X_test: (20, 5)

Contoh One-Hot Encoding:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

Contoh Data Normalisasi & Outlier Handling:
Sebelum (Data Asli): [ 9.96714153  3.61735699 11.47688538 20.23029856  2.65846625]
Sesudah Normalisasi: [ 0.604418   -0.21979528  0.75746006  1.461092   -0.18919425]
Sesudah Outlier Handling: [ 0.604418   -0.21979528  0.75746006  1.461092   -0.18919425]
